apiVersion: v1
kind: Service
metadata: boxing-service
spec:
	selector:
	app: boxingapp #select the boxing pod and expose
	type: LoadBalancer
	ports:
-	protocol: TCP
-	port: 8000
-	targetPort: 3000

apiVersion: apps/v1
kind: Deployment
metadata:
	name: boxer-deployment
spec:
	replicas: 1
	selector:
		matchlabels:
		app: boxingapp
	template:
		metadata:
		labels:
			app: boxingapp #label by which pod can be used
spec:
containers:
Name: boxingapp
Image: adewaletalabi/boxingappimage:latest
Env:
-	name: MONGODB_CONNECTION_URI
-	value: “mongodb+srv://awodi:ireniwaju148@cluster0.9nres.mongodb.net/”
-	name: AUTH_API_ADDRESS
-	value: “auth-service.default:3000”
